name: Build and Test
on: [push]
jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libgc-dev
          tar xvzf dep/obnc_0.16.1.tar.gz
          tar xvzf dep/obnc-libext_0.7.0.tar.gz
          cd obnc-0.16.1; ./build; sudo ./install
          cd ../obnc-libext-0.7.0; ./build; sudo ./install
          pip install numpy

      - name: Build
        run: |
          make clean
          make all

      - name: Test
        run: |
          dd if=/dev/zero of=tests/b-foo-9-96-4-28-28-28-28-0-0-0.pex bs=1 count=0 seek=534528
          dd if=/dev/zero of=tests/b-foo-9-96-4-28-28-28-28-32-32-32-40-0-0-0.dnd bs=1 count=0 seek=2052587520
          make test

  MacOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: | 
          brew install SDL2
          which gfortran-9
          ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          tar xvzf dep/obnc_0.16.1.tar.gz
          tar xvzf dep/obnc-libext_0.7.0.tar.gz
          cd obnc-0.16.1; ./build; ./install
          cd ../obnc-libext-0.7.0; ./build; ./install
          pip3 install numpy

      - name: Build
        run: |
          make clean
          make all

      - name: Test
        run: |
          dd if=/dev/zero of=tests/b-foo-9-96-4-28-28-28-28-0-0-0.pex bs=1 count=0 seek=534528
          dd if=/dev/zero of=tests/b-foo-9-96-4-28-28-28-28-32-32-32-40-0-0-0.dnd bs=1 count=0 seek=2052587520
          make test

  Windows-build:
    runs-on: windows-latest
    steps:
      - name: Add Msys64 to PATH
        if: matrix.os == 'windows-latest'
        run: echo "::add-path::/c/msys64/mingw64/bin:/c/msys64/usr/bin"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: | 
          pwd
          mv dep/obnc_0.16.1_win32.zip ./
          7z x obnc_0.16.1_win32.zip
          echo "------------obnc-0.16.1---------------"
          ls obnc-0.16.1/
          cp -a obnc-0.16.1/* /c/msys64/usr/bin/
          pip install numpy

          #obnc -h
          cat obnc-0.16.1/README.txt
          cat obnc-0.16.1/obnc.bat
          cat obnc-0.16.1/obnc-path.bat
          cat obnc-0.16.1/obnc-compile.bat

          #brew install SDL2
          #which gfortran-9
          #ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          #wget http://miasap.se/obnc/downloads/obnc_0.16.1.tar.gz; tar xvzf obnc_0.16.1.tar.gz
          #wget http://miasap.se/obnc/downloads/obnc-libext_0.7.0.tar.gz; tar xvzf obnc-libext_0.7.0.tar.gz
          #cd obnc-0.16.1; ./build; ./install
          #cd ../obnc-libext-0.7.0; ./build; ./install
        shell: bash

      - name: Build
        run: |
          make clean
          make cbrainiac
          make fbrainiac
          #make obrainiac
          make gobrainiac
          make Brainiac.jar
        shell: bash

      - name: Test
        run: |
          cd tests
          FSUtil File CreateNew b-foo-9-96-4-28-28-28-28-0-0-0.pex 0x82800
          FSUtil Sparse SetFlag b-foo-9-96-4-28-28-28-28-0-0-0.pex
          FSUtil Sparse SetRange b-foo-9-96-4-28-28-28-28-0-0-0.pex 0 0x82800
          FSUtil File CreateNew b-foo-9-96-4-28-28-28-28-32-32-32-40-0-0-0.dnd 0x7A580000
          FSUtil Sparse SetFlag b-foo-9-96-4-28-28-28-28-32-32-32-40-0-0-0.dnd
          FSUtil Sparse SetRange b-foo-9-96-4-28-28-28-28-32-32-32-40-0-0-0.dnd 0 0x7A580000
          ../cbrainiac foo
          ../fbrainiac foo
          #./obrainiac tests/commontest
          ../gobrainiac foo
          python3 ../src/brainiac/brainiac.py foo
          java -jar ../Brainiac.jar foo
        shell: bash

