name: Build and Test
on: [push]
jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Build
        run: |
          make clean
          make cbrainiac
          make fbrainiac
          make gobrainiac
          #cd oxfsgo
          #go get github.com/io-core/oxfs-linux/oxfsgo
          #go build cmd/oxfstool.go

      - name: Test
        run: |
          ls
          ./cbrainiac tests/commontest
          ./fbrainiac tests/commontest
          ./gobrainiac tests/commontest
          #cd oxfsgo/test
          #bash test.sh

  MacOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: | 
          brew install SDL2
          brew install --cask gfortran
          brew install wget

      - name: Build
        run: |
          make clean
          make cbrainiac
          make fbrainiac
          make gobrainiac
          #cd oxfsgo
          #go get github.com/io-core/oxfs-linux/oxfsgo
          #go build cmd/oxfstool.go

      - name: Test
        run: |
          ls
          ./cbrainiac tests/commontest
          ./fbrainiac tests/commontest
          ./gobrainiac tests/commontest
          #cd oxfsgo/test
          #bash test.sh


