name: Build and Test
on: [push]
jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libgc-dev
          wget http://miasap.se/obnc/downloads/obnc_0.16.1.tar.gz; tar xvzf obnc_0.16.1.tar.gz
          wget http://miasap.se/obnc/downloads/obnc-libext_0.7.0.tar.gz; tar xvzf obnc-libext_0.7.0.tar.gz
          cd obnc-0.16.1; ./build; sudo ./install
          cd ../obnc-libext-0.7.0; ./build; sudo ./install


      - name: Build
        run: |
          make clean
          make all

      - name: Test
        run: |
          make test

  MacOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: | 
          brew install SDL2
          which gfortran-9
          ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          wget http://miasap.se/obnc/downloads/obnc_0.16.1.tar.gz; tar xvzf obnc_0.16.1.tar.gz
          wget http://miasap.se/obnc/downloads/obnc-libext_0.7.0.tar.gz; tar xvzf obnc-libext_0.7.0.tar.gz
          cd obnc-0.16.1; ./build; ./install
          cd ../obnc-libext-0.7.0; ./build; ./install
          

      - name: Build
        run: |
          make clean
          make all

      - name: Test
        run: |
          make test

  Windows-build:
    runs-on: windows-latest
    steps:
      - name: Add Msys64 to PATH
        if: matrix.os == 'windows-latest'
        run: echo "::add-path::/c/msys64/mingw64/bin:/c/msys64/usr/bin"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: GetGo  
        uses: actions/setup-go@v2
        with:
            go-version: '1.9.3'

      - name: Install Dependencies
        run: | 
          pwd
          curl -fsSL -o obnc.zip https://miasap.se/obnc/downloads/obnc_0.16.1_win32.zip 
          7z x obnc.zip
          echo "------------obnc-0.16.1---------------"
          ls obnc-0.16.1/
          cp -a obnc-0.16.1/* /c/msys64/usr/bin/
          
          #obnc -h
          cat obnc-0.16.1/README.txt
          cat obnc-0.16.1/obnc.bat
          cat obnc-0.16.1/obnc-path.bat
          cat obnc-0.16.1/obnc-compile.bat

          #brew install SDL2
          #which gfortran-9
          #ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          #wget http://miasap.se/obnc/downloads/obnc_0.16.1.tar.gz; tar xvzf obnc_0.16.1.tar.gz
          #wget http://miasap.se/obnc/downloads/obnc-libext_0.7.0.tar.gz; tar xvzf obnc-libext_0.7.0.tar.gz
          #cd obnc-0.16.1; ./build; ./install
          #cd ../obnc-libext-0.7.0; ./build; ./install
        shell: bash

      - name: Build
        run: |
          make clean
          make cbrainiac
          make fbrainiac
          #make obrainiac
          make gobrainiac
          make Brainiac.class
        shell: bash

      - name: Test
        run: |
          ls
          ./cbrainiac tests/commontest
          ./fbrainiac tests/commontest
          #./obrainiac tests/commontest
          ./gobrainiac tests/commontest
          python3 src/brainiac/brainiac.py tests/commontest
          java Brainiac tests/commontest
        shell: bash

